services:
    app:
      image: node:latest
      working_dir: /usr/src/app
      tty: true
      ports: 
      - '3000:3000'
      volumes:
        - ./:/usr/src/app
      command: >
        bash -c "npm install &&
        npm i -D typescript ts-node tsconfig-paths @types/node jest ts-jest @types/jest && bash"